export const carCompanies = [
    {
        companyId: '1',
        companyName: 'Alfa Romeo',
    },
    {
        companyId: '2',
        companyName: 'Alpine',
    },
    {
        companyId: '3',
        companyName: 'BMW',
    },
    {
        companyId: '4',
        companyName: 'Cadillac',
    },
    {
        companyId: '5',
        companyName: 'Chevrolet',
    },
    {
        companyId: '6',
        companyName: 'Daihatsu',
    },
    {
        companyId: '7',
        companyName: 'Dodge',
    },
    {
        companyId: '8',
        companyName: 'Ford',
    },
    {
        companyId: '9',
        companyName: 'Honda',
    },
    {
        companyId: '10',
        companyName: 'Dodge',
    },
    {
        companyId: '11',
        companyName: 'Infiniti',
    },
    {
        companyId: '12',
        companyName: 'Isuzu',
    },
    {
        companyId: '13',
        companyName: 'Lamborghini',
    },
    {
        companyId: '14',
        companyName: 'Lexus',
    },
    {
        companyId: '15',
        companyName: 'Lotus',
    },
    {
        companyId: '16',
        companyName: 'Mazda',
    },
    {
        companyId: '17',
        companyName: 'Mercedes-Benz',
    },
    {
        companyId: '18',
        companyName: 'Mini',
    },
    {
        companyId: '19',
        companyName: 'Mitsubishi',
    },
];

export const carFreePartsSelect = [
    {
        partId: '1',
        partName: 'Muffler',
    },
    {
        partId: '2',
        partName: 'Turbo',
    },
    {
        partId: '3',
        partName: 'Clutch',
    },
    {
        partId: '4',
        partName: 'Shaft',
    },
    {
        partId: '5',
        partName: 'Bar',
    },
];

export const cars = [
    {
        companyId: '9',
        car: [
            {
                carId: '01',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC1.png'),
                speed: 3497,
                acceleration: 2211,
                handling: 4475,
                nitrous: 3896,
                gasUsage: 810,
            },
            {
                carId: '02',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC2.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '03',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC3.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '04',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC4.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '05',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC5.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '06',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC5.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '07',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC7.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '08',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC8.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '09',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC9.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '10',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC10.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '11',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC11.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '12',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC12.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '13',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC13.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '14',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC14.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '15',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC15.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '16',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC16.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '17',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC17.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '18',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC18.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '19',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC19.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '20',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC20.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '21',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC21.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '22',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC22.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '23',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC23.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '24',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC24.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '25',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC25.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '26',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC26.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '27',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC27.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '28',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC28.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '29',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC29.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '30',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC30.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '31',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC31.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '32',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC32.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '33',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC33.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '34',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC34.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '35',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC35.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '36',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC36.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '37',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC37.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '38',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC38.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '39',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC39.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '40',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC40.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '41',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC41.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '42',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC42.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '43',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC43.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '44',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC44.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '45',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC45.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '46',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC46.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '47',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC47.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '48',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC48.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '49',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC49.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '50',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC50.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '51',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC51.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '52',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC52.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '53',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC53.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '54',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC54.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '55',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC55.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '56',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC56.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '57',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC57.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '58',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC58.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '59',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC59.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '60',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC60.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '61',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC61.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '62',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC62.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '63',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC63.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '64',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC64.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '65',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC65.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '66',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC66.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '67',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC67.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '68',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC68.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '69',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC69.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '70',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC70.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '71',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC71.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
            {
                carId: '72',
                // power: 1000,
                image: require('../assets/images/carsimg/honda/HondaC72.png'),
                speed: 100,
                acceleration: 50,
                handling: 10,
                nitrous: 20,
                gasUsage: 30,
            },
        ],
    },
];

export const carParts = [
    {
        carPartsId: '001',
        engine: [
            {
                id: 'e1',
                power: 5,
                maximum: 50,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr1Engine.png'),
            },
            {
                id: 'e2',
                power: 10,
                maximum: 105,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr2Engine.png'),
            },
            {
                id: 'e3',
                power: 15,
                maximum: 160,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr3Engine.png'),
            },
            {
                id: 'e4',
                power: 20,
                maximum: 215,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr4Engine.png'),
            },
            {
                id: 'e5',
                power: 25,
                maximum: 270,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr5Engine.png'),
            },
            {
                id: 'e6',
                power: 30,
                maximum: 325,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr6Engine.png'),
            },
            {
                id: 'e7',
                power: 35,
                maximum: 380,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr7Engine.png'),
            },
            {
                id: 'e8',
                power: 40,
                maximum: 435,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr8Engine.png'),
            },
            {
                id: 'e9',
                power: 45,
                maximum: 490,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr9Engine.png'),
            },
            {
                id: 'e10',
                power: 50,
                maximum: 545,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr10Engine.png'),
            },
            {
                id: 'e11',
                power: 55,
                maximum: 600,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr11Engine.png'),
            },
            {
                id: 'e12',
                power: 60,
                maximum: 655,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr12Engine.png'),
            },
            {
                id: 'e13',
                power: 65,
                maximum: 710,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr13Engine.png'),
            },
            {
                id: 'e14',
                power: 70,
                maximum: 765,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr14Engine.png'),
            },
            {
                id: 'e15',
                power: 80,
                maximum: 820,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr15Engine.png'),
            },
            {
                id: 'e16',
                power: 80,
                maximum: 875,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr16Engine.png'),
            },
            {
                id: 'e17',
                power: 85,
                maximum: 930,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr17Engine.png'),
            },
            {
                id: 'e18',
                power: 90,
                maximum: 985,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr18Engine.png'),
            },
            {
                id: 'e19',
                power: 95,
                maximum: 1040,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr20Engine.png'),
            },
            {
                id: 'e20',
                power: 100,
                maximum: 1095,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr20Engine.png'),
            },
            {
                id: 'e21',
                power: 210,
                maximum: 1255,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr21Engine.png'),
            },
            {
                id: 'e22',
                power: 220,
                maximum: 1315,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr22Engine.png'),
            },
            {
                id: 'e23',
                power: 230,
                maximum: 1375,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr23Engine.png'),
            },
            {
                id: 'e24',
                power: 240,
                maximum: 1435,
                type: 'engine',
                image: require('../assets/images/carParts/grEngine/Gr24Engine.png'),
            },
        ],
        transmission: [
            {
                id: 'tra1',
                power: 5,
                maximum: 50,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr1Trans.png'),
            },
            {
                id: 'tra2',
                power: 10,
                maximum: 105,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr2Trans.png'),
            },
            {
                id: 'tra3',
                power: 15,
                maximum: 160,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr3Trans.png'),
            },
            {
                id: 'tra4',
                power: 20,
                maximum: 215,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr4Trans.png'),
            },
            {
                id: 'tra5',
                power: 25,
                maximum: 270,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr5Trans.png'),
            },
            {
                id: 'tra6',
                power: 30,
                maximum: 325,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr6Trans.png'),
            },
            {
                id: 'tra7',
                power: 35,
                maximum: 380,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr7Trans.png'),
            },
            {
                id: 'tra8',
                power: 40,
                maximum: 435,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr8Trans.png'),
            },
            {
                id: 'tra9',
                power: 45,
                maximum: 490,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr9Trans.png'),
            },
            {
                id: 'tra10',
                power: 50,
                maximum: 545,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr10Trans.png'),
            },
            {
                id: 'tra11',
                power: 55,
                maximum: 600,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr11Trans.png'),
            },
            {
                id: 'tra12',
                power: 60,
                maximum: 655,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr12Trans.png'),
            },
            {
                id: 'tra13',
                power: 65,
                maximum: 710,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr13Trans.png'),
            },
            {
                id: 'tra14',
                power: 70,
                maximum: 765,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr14Trans.png'),
            },
            {
                id: 'tra15',
                power: 80,
                maximum: 820,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr15Trans.png'),
            },
            {
                id: 'tra16',
                power: 80,
                maximum: 875,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr16Trans.png'),
            },
            {
                id: 'tra17',
                power: 85,
                maximum: 930,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr17Trans.png'),
            },
            {
                id: 'tra18',
                power: 90,
                maximum: 985,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr18Trans.png'),
            },
            {
                id: 'tra19',
                power: 95,
                maximum: 1040,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr20Trans.png'),
            },
            {
                id: 'tra20',
                power: 100,
                maximum: 1095,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr20Trans.png'),
            },
            {
                id: 'tra21',
                power: 210,
                maximum: 1255,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr21Trans.png'),
            },
            {
                id: 'tra22',
                power: 220,
                maximum: 1315,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr22Trans.png'),
            },
            {
                id: 'tra23',
                power: 230,
                maximum: 1375,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr23Trans.png'),
            },
            {
                id: 'tra24',
                power: 240,
                maximum: 1435,
                type: 'transmission',
                image: require('../assets/images/carParts/trans/Gr24Trans.png'),
            },
        ],
        clutch: [
            {
                id: 'c1',
                power: 5,
                maximum: 50,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr1Clutch.png'),
            },
            {
                id: 'c2',
                power: 10,
                maximum: 105,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr2Clutch.png'),
            },
            {
                id: 'c3',
                power: 15,
                maximum: 160,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr3Clutch.png'),
            },
            {
                id: 'c4',
                power: 20,
                maximum: 215,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr4Clutch.png'),
            },
            {
                id: 'c5',
                power: 25,
                maximum: 270,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr5Clutch.png'),
            },
            {
                id: 'c6',
                power: 30,
                maximum: 325,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr6Clutch.png'),
            },
            {
                id: 'c7',
                power: 35,
                maximum: 380,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr7Clutch.png'),
            },
            {
                id: 'c8',
                power: 40,
                maximum: 435,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr8Clutch.png'),
            },
            {
                id: 'c9',
                power: 45,
                maximum: 490,
                type: 'clutch',
                image: require('../assets/images/carParts/clutch/Gr9Clutch.png'),
            },
        ],
        bar: [
            {
                id: 'b1',
                power: 5,
                type: 'bar',
                maximum: 50,
                image: require('../assets/images/carParts/grBar/Gr1Bar.png'),
            },
            {
                id: 'b2',
                power: 10,
                type: 'bar',
                maximum: 105,
                image: require('../assets/images/carParts/grBar/Gr2Bar.png'),
            },
            {
                id: 'b3',
                power: 15,
                type: 'bar',
                maximum: 160,
                image: require('../assets/images/carParts/grBar/Gr3Bar.png'),
            },
            {
                id: 'b4',
                power: 20,
                type: 'bar',
                maximum: 215,
                image: require('../assets/images/carParts/grBar/Gr4Bar.png'),
            },
            {
                id: 'b5',
                power: 25,
                type: 'bar',
                maximum: 270,
                image: require('../assets/images/carParts/grBar/Gr5Bar.png'),
            },
            {
                id: 'b6',
                power: 30,
                type: 'bar',
                maximum: 325,
                image: require('../assets/images/carParts/grBar/Gr6Bar.png'),
            },
            {
                id: 'b7',
                power: 35,
                type: 'bar',
                maximum: 380,
                image: require('../assets/images/carParts/grBar/Gr7Bar.png'),
            },
            {
                id: 'b8',
                power: 40,
                type: 'bar',
                maximum: 435,
                image: require('../assets/images/carParts/grBar/Gr8Bar.png'),
            },
            {
                id: 'b9',
                power: 45,
                type: 'bar',
                maximum: 490,
                image: require('../assets/images/carParts/grBar/Gr9Bar.png'),
            },
            {
                id: 'b10',
                power: 50,
                type: 'bar',
                maximum: 545,
                image: require('../assets/images/carParts/grBar/Gr10Bar.png'),
            },
        ],
        shaft: [
            {
                id: 's1',
                power: 5,
                maximum: 50,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr1Shaft.png'),
            },
            {
                id: 's2',
                power: 10,
                maximum: 105,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr2Shaft.png'),
            },
            {
                id: 's3',
                power: 15,
                maximum: 160,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr3Shaft.png'),
            },
            {
                id: 's4',
                power: 20,
                maximum: 215,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr4Shaft.png'),
            },
            {
                id: 's5',
                power: 25,
                maximum: 270,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr5Shaft.png'),
            },
            {
                id: 's6',
                power: 30,
                maximum: 325,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr6Shaft.png'),
            },
            {
                id: 's7',
                power: 35,
                maximum: 380,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr7Shaft.png'),
            },
            {
                id: 's8',
                power: 40,
                maximum: 435,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr8Shaft.png'),
            },
            {
                id: 's9',
                power: 45,
                maximum: 490,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr9Shaft.png'),
            },
            {
                id: 's10',
                power: 50,
                maximum: 545,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr10Shaft.png'),
            },
            {
                id: 's11',
                power: 55,
                maximum: 600,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr11Shaft.png'),
            },
            {
                id: 's12',
                power: 60,
                maximum: 655,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr12Shaft.png'),
            },
            {
                id: 's13',
                power: 65,
                maximum: 710,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr13Shaft.png'),
            },
            {
                id: 's14',
                power: 70,
                maximum: 765,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr14Shaft.png'),
            },
            {
                id: 's15',
                power: 80,
                maximum: 820,
                type: 'shaft',
                image: require('../assets/images/carParts/shaft/Gr15Shaft.png'),
            },
        ],
        muffler: [
            {
                id: 'm1',
                power: 5,
                maximum: 50,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr1Muffler.png'),
            },
            {
                id: 'm2',
                power: 10,
                maximum: 105,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr2Muffler.png'),
            },
            {
                id: 'm3',
                power: 15,
                maximum: 160,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr3Muffler.png'),
            },
            {
                id: 'm4',
                power: 20,
                maximum: 215,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr4Muffler.png'),
            },
            {
                id: 'm5',
                power: 25,
                maximum: 270,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr5Muffler.png'),
            },
            {
                id: 'm6',
                power: 30,
                maximum: 325,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr6Muffler.png'),
            },
            {
                id: 'm7',
                power: 35,
                maximum: 380,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr7Muffler.png'),
            },
            {
                id: 'm8',
                power: 40,
                maximum: 435,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr8Muffler.png'),
            },
            {
                id: 'm9',
                power: 45,
                maximum: 490,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr9Muffler.png'),
            },
            {
                id: 'm10',
                power: 50,
                maximum: 545,
                type: 'muffler',
                image: require('../assets/images/carParts/grMuffler/Gr10Muffler.png'),
            },
        ],
        turbo: [
            {
                id: 't1',
                power: 5,
                maximum: 50,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr1Turbo.png'),
            },
            {
                id: 't2',
                power: 10,
                maximum: 105,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr2Turbo.png'),
            },
            {
                id: 't3',
                power: 15,
                maximum: 160,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr3Turbo.png'),
            },
            {
                id: 't4',
                power: 20,
                maximum: 215,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr4Turbo.png'),
            },
            {
                id: 't5',
                power: 25,
                maximum: 270,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr5Turbo.png'),
            },
            {
                id: 't6',
                power: 30,
                maximum: 325,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr6Turbo.png'),
            },
            {
                id: 't7',
                power: 35,
                maximum: 380,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr7Turbo.png'),
            },
            {
                id: 't8',
                power: 40,
                maximum: 435,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr8Turbo.png'),
            },
            {
                id: 't9',
                power: 45,
                maximum: 490,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr9Turbo.png'),
            },
            {
                id: 't10',
                power: 50,
                maximum: 545,
                type: 'turbo',
                image: require('../assets/images/carParts/grTurbo/Gr10Turbo.png'),
            },
        ],
        tire: [
            {
                id: 'tr1',
                power: 5,
                type: 'tire',
                maximum: 50,
                image: require('../assets/images/carParts/tire/Gr1Tires.png'),
            },
            {
                id: 'tr2',
                power: 10,
                type: 'tire',
                maximum: 105,
                image: require('../assets/images/carParts/tire/Gr2Tires.png'),
            },
            {
                id: 'tr3',
                power: 15,
                type: 'tire',
                maximum: 160,
                image: require('../assets/images/carParts/tire/Gr3Tires.png'),
            },
            {
                id: 'tr4',
                power: 20,
                type: 'tire',
                maximum: 215,
                image: require('../assets/images/carParts/tire/Gr4Tires.png'),
            },
            {
                id: 'tr5',
                power: 25,
                type: 'tire',
                maximum: 270,
                image: require('../assets/images/carParts/tire/Gr5Tires.png'),
            },
            {
                id: 'tr6',
                power: 30,
                type: 'tire',
                maximum: 325,
                image: require('../assets/images/carParts/tire/Gr6Tires.png'),
            },
            {
                id: 'tr7',
                power: 35,
                type: 'tire',
                maximum: 380,
                image: require('../assets/images/carParts/tire/Gr7Tires.png'),
            },
            {
                id: 'tr8',
                power: 40,
                type: 'tire',
                maximum: 435,
                image: require('../assets/images/carParts/tire/Gr8Tires.png'),
            },
            {
                id: 'tr9',
                power: 45,
                type: 'tire',
                maximum: 490,
                image: require('../assets/images/carParts/tire/Gr9Tires.png'),
            },
            {
                id: 'tr10',
                power: 50,
                type: 'tire',
                maximum: 545,
                image: require('../assets/images/carParts/tire/Gr10Tires.png'),
            },
            {
                id: 'tr11',
                power: 55,
                type: 'tire',
                maximum: 600,
                image: require('../assets/images/carParts/tire/Gr11Tires.png'),
            },
            {
                id: 'tr12',
                power: 60,
                type: 'tire',
                maximum: 655,
                image: require('../assets/images/carParts/tire/Gr12Tires.png'),
            },
            {
                id: 'tr13',
                power: 65,
                type: 'tire',
                maximum: 710,
                image: require('../assets/images/carParts/tire/Gr13Tires.png'),
            },
            {
                id: 'tr14',
                power: 70,
                type: 'tire',
                maximum: 765,
                image: require('../assets/images/carParts/tire/Gr14Tires.png'),
            },
            {
                id: 'tr15',
                power: 80,
                type: 'tire',
                maximum: 820,
                image: require('../assets/images/carParts/tire/Gr15Tires.png'),
            },
            {
                id: 'tr16',
                power: 80,
                type: 'tire',
                maximum: 875,
                image: require('../assets/images/carParts/tire/Gr16Tires.png'),
            },
            {
                id: 'tr17',
                power: 85,
                type: 'tire',
                maximum: 930,
                image: require('../assets/images/carParts/tire/Gr17Tires.png'),
            },
            {
                id: 'tr18',
                power: 90,
                type: 'tire',
                maximum: 985,
                image: require('../assets/images/carParts/tire/Gr18Tires.png'),
            },
            {
                id: 'tr19',
                power: 95,
                type: 'tire',
                maximum: 1040,
                image: require('../assets/images/carParts/tire/Gr19Tires.png'),
            },
            {
                id: 'tr20',
                power: 100,
                type: 'tire',
                maximum: 1095,
                image: require('../assets/images/carParts/tire/Gr20Tires.png'),
            },
            {
                id: 'tr21',
                power: 210,
                type: 'tire',
                maximum: 1255,
                image: require('../assets/images/carParts/tire/Gr21Tires.png'),
            },
            {
                id: 'tr22',
                power: 220,
                type: 'tire',
                maximum: 1315,
                image: require('../assets/images/carParts/tire/Gr22Tires.png'),
            },
            {
                id: 'tr23',
                power: 230,
                type: 'tire',
                maximum: 1375,
                image: require('../assets/images/carParts/tire/Gr23Tires.png'),
            },
            {
                id: 'tr24',
                power: 240,
                type: 'tire',
                maximum: 1435,
                image: require('../assets/images/carParts/tire/Gr24Tires.png'),
            },
        ],
        Nitro: [
            {
                id: 'n1',
                power: 5,
                maximum: 50,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr1Nitro.png'),
            },
            {
                id: 'n2',
                power: 10,
                maximum: 105,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr2Nitro.png'),
            },
            {
                id: 'n3',
                power: 15,
                maximum: 160,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr3Nitro.png'),
            },
            {
                id: 'n4',
                power: 20,
                maximum: 215,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr4Nitro.png'),
            },
            {
                id: 'n5',
                power: 25,
                maximum: 270,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr5Nitro.png'),
            },
            {
                id: 'n6',
                power: 30,
                maximum: 325,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr6Nitro.png'),
            },
            {
                id: 'n7',
                power: 35,
                maximum: 380,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr7Nitro.png'),
            },
            {
                id: 'n8',
                power: 40,
                maximum: 435,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr8Nitro.png'),
            },
            {
                id: 'n9',
                power: 45,
                maximum: 490,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr9Nitro.png'),
            },
            {
                id: 'n10',
                power: 50,
                maximum: 545,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr10Nitro.png'),
            },
            {
                id: 'n11',
                power: 55,
                maximum: 600,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr11Nitro.png'),
            },
            {
                id: 'n12',
                power: 60,
                maximum: 655,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr12Nitro.png'),
            },
            {
                id: 'n13',
                power: 65,
                maximum: 710,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr13Nitro.png'),
            },
            {
                id: 'n14',
                power: 70,
                maximum: 765,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr14Nitro.png'),
            },
            {
                id: 'n15',
                power: 80,
                maximum: 820,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr15Nitro.png'),
            },
            {
                id: 'n16',
                power: 80,
                maximum: 875,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr16Nitro.png'),
            },
            {
                id: 'n17',
                power: 85,
                maximum: 930,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr17Nitro.png'),
            },
            {
                id: 'n18',
                power: 90,
                maximum: 985,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr18Nitro.png'),
            },
            {
                id: 'n19',
                power: 95,
                maximum: 1040,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr20Nitro.png'),
            },
            {
                id: 'n20',
                power: 100,
                maximum: 1095,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr20Nitro.png'),
            },
            {
                id: 'n21',
                power: 210,
                maximum: 1255,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr21Nitro.png'),
            },
            {
                id: 'n22',
                power: 220,
                maximum: 1315,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr22Nitro.png'),
            },
            {
                id: 'n23',
                power: 230,
                maximum: 1375,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr23Nitro.png'),
            },
            {
                id: 'n24',
                power: 240,
                maximum: 1435,
                type: 'nitrous',
                image: require('../assets/images/carParts/grNitro/Gr24Nitro.png'),
            },
        ],
        ECU: [
            {
                id: 'ec1',
                Gas: -5,
                maximum: -14,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr1ECU.png'),
            },
            {
                id: 'ec2',
                Gas: -10,
                maximum: -29,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr2ECU.png'),
            },
            {
                id: 'ec3',
                Gas: -15,
                maximum: -44,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr3ECU.png'),
            },
            {
                id: 'ec4',
                Gas: -20,
                maximum: -59,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr4ECU.png'),
            },
            {
                id: 'ec5',
                Gas: -25,
                maximum: -74,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr5ECU.png'),
            },
            {
                id: 'ec6',
                Gas: -30,
                maximum: -89,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr6ECU.png'),
            },
            {
                id: 'ec7',
                Gas: -35,
                maximum: -104,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr7ECU.png'),
            },
            {
                id: 'ec8',
                Gas: -40,
                maximum: -119,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr8ECU.png'),
            },
            {
                id: 'ec9',
                Gas: -45,
                maximum: -134,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr9ECU.png'),
            },
            {
                id: 'ec10',
                Gas: -50,
                maximum: -149,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr10ECU.png'),
            },
            {
                id: 'ec11',
                Gas: -55,
                maximum: -164,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr11ECU.png'),
            },
            {
                id: 'ec12',
                Gas: -60,
                maximum: -179,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr12ECU.png'),
            },
            {
                id: 'ec13',
                Gas: -65,
                maximum: -194,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr13ECU.png'),
            },
            {
                id: 'ec14',
                Gas: -70,
                maximum: -209,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr14ECU.png'),
            },
            {
                id: 'ec15',
                Gas: -75,
                maximum: -224,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr15ECU.png'),
            },
            {
                id: 'ec16',
                Gas: -80,
                maximum: -239,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr16ECU.png'),
            },
            {
                id: 'ec17',
                Gas: -85,
                maximum: -254,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr17ECU.png'),
            },
            {
                id: 'ec18',
                Gas: -90,
                maximum: -269,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr18ECU.png'),
            },
            {
                id: 'ec19',
                Gas: -95,
                maximum: -284,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr20ECU.png'),
            },
            {
                id: 'ec20',
                Gas: -100,
                maximum: -299,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr20ECU.png'),
            },
            {
                id: 'ec21',
                Gas: -105,
                maximum: -314,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr21ECU.png'),
            },
            {
                id: 'ec22',
                Gas: -110,
                maximum: -329,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr22ECU.png'),
            },
            {
                id: 'ec23',
                Gas: -115,
                maximum: -344,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr23ECU.png'),
            },
            {
                id: 'ec24',
                Gas: -120,
                maximum: -359,
                type: 'ecu',
                image: require('../assets/images/carParts/grECU/Gr24ECU.png'),
            },
        ],
    },
];
